[package]
name = "dimension_expander"
version = "0.1.0"
authors = ["Marko Mijalkovic <marko.mijalkovic97@gmail.com>"]

[dependencies]
vst2 = { path = "../.." }
time = "0.1"

[lib]
name = "dimension_expander"
crate-type = ["cdylib"]
